=== inad9300/RESTyle/Engine/src/main/resources/specification/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "version": {
            "type": "string"
        },
        "baseUrl": {
            "type": "string",
            "pattern": "^(http(?:s)?\\:\\/\\/[a-zA-Z0-9]+(?:(?:\\.|\\-)[a-zA-Z0-9]+)+(?:\\:\\d+)?(?:\\/[\\w\\-]+)*(?:\\/?|\\/\\w+\\.[a-zA-Z]{2,4}(?:\\?[\\w]+\\=[\\w\\-]+)?)?(?:\\&[\\w]+\\=[\\w\\-]+)*)$"
        },
        "dataFormats": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^([\\w.+-]+/[\\w.+-]+)$"
            },
            "uniqueItems": true,
            "minItems": 1
        },
        "authenticationMechanism": {
            "type": "string"
        },
        "encoding": {
            "type": "string"
        },
        "timeZone": {
            "type": "string"
        },
        "dateFormat": {
            "type": "string"
        },
        "roles": {
            "type": "array",
            "items": { "$ref": "#/definitions/role" },
            "uniqueItems": true,
            "minItems": 0
        },
        "database": {
            "type": "object",
            "properties": {
                "dbms": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "prefix": {
                    "type": "string"
                },
                "admin": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "password": {
                            "type": "string"
                        }
                    },
                    "required": ["name", "password"]
                }
            }
        },
        "types": {
            "type": "array",
            "items": { "$ref": "#/definitions/field" },
            "uniqueItems": true,
            "minItems": 0
        },
        "resources": {
            "type": "array",
            "items": { "$ref": "#/definitions/resource" },
            "uniqueItems": true,
            "minItems": 1
        }
    },
    "required": ["baseUrl", "dataFormats", "database", "resources"],
    "additionalProperties": true,

    "definitions": {

        "role": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "isAdmin": {
                    "type": "boolean"
                },
                "isGuest": {
                    "type": "boolean"
                },
                "isA": {
                    "type": "string"
                },
                "rateLimit": {
                    "type": "object",
                    "properties": {
                        "numOfRequests": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "refreshTime": {
                            "type": "integer",
                            "minimum": 0
                        }
                    },
                    "required": ["numOfRequests", "refreshTime"]
                }
            },
            "required": ["name"]
        },

        "check": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true,
            "minItems": 0
        },

        "index": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true,
            "minItems": 0
        },

        "resource": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "plural": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "base": {
                    "type": "string"
                },
                "abstract": {
                    "type": "boolean"
                },
                "inheritanceStrategy": {
                    "type": "string"
                },
                "paginable": {
                    "type": "boolean"
                },
                "idInjection": {
                    "type": "boolean"
                },
                "fields": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/field" },
                    "uniqueItems": true,
                    "minItems": 1
                },
                "acceptExtraFields": {
                    "type": "boolean"
                },
                "relations": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/relation" },
                    "uniqueItems": true,
                    "minItems": 0
                },
                "check": { "$ref": "#/definitions/check" },
                "index": { "$ref": "#/definitions/index" },
                "acl": { "$ref": "#/definitions/acl" }
            },
            "required": ["name", "fields"]
        },

        "field": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                },
                "min": {
                    "type": "integer"
                },
                "max": {
                    "type": "integer"
                },
                "enum": {
                    "type": "array",
                    "uniqueItems": true,
                    "minItems": 1
                },
                "precision": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "uniqueItems": false,
                    "minItems": 2,
                    "maxItems": 2
                },
                "default": {},
                "onUpdate": {
                    "type": "string"
                },
                "unique": {
                    "type": "boolean"
                },
                "pattern": {
                    "type": "string"
                },
                "filterable": {
                    "type": "boolean"
                },
                "sortable": {
                    "type": "boolean"
                },
                "readOnly": {
                    "type": "boolean"
                },
                "writeOnly": {
                    "type": "boolean"
                },
                "encrypted": {
                    "type": "boolean"
                }
            },
            "required": ["name", "type"]
        },

        "relation": {
            "type": "object",
            "properties": {
                "with": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": ["hasOne", "hasMany"]
                },
                "min": {
                    "type": "integer"
                },
                "max": {
                    "type": "integer"
                },
                "embed": {
                    "type": "boolean"
                },
                "onDelete": {
                    "type": "string"
                },
                "onUpdate": {
                    "type": "string"
                },
                "fields": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/field" },
                    "uniqueItems": true,
                    "minItems": 0
                },
                "check": { "$ref": "#/definitions/check" },
                "index": { "$ref": "#/definitions/index" }
            },
            "required": ["with", "type"]
        },

        "aclSimple": {
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^([a-zA-Z0-9_]{1,}(\\+[a-zA-Z0-9_]{1,}){0,1})$"
            },
            "uniqueItems": true,
            "minItems": 0
        },

        "acl": {
            "oneOf": [
                { "$ref": "#/definitions/aclSimple" },
                {
                    "type": "object",
                    "properties": {
                        "read": { "$ref": "#/definitions/aclSimple" },
                        "create": { "$ref": "#/definitions/aclSimple" },
                        "update": { "$ref": "#/definitions/aclSimple" },
                        "delete": { "$ref": "#/definitions/aclSimple" }
                    }
                }
            ]
        }

    }
}

=== inad9300/RESTyle/Engine/src/main/resources/examples/spec.json
{
    "title": "Bookstore",
    "description": "The best bookstore ever",
    "version": "v1",
    "baseUrl": "https://api.bookstore.example.org/{version}/",
    "dataFormats": ["application/json", "text/xml"],
    "encoding": "UTF-8",
    "timeZone": "UTC",
    "dateFormat": "ISO-8601",
    "roles": [
        { "name": "admin", "isAdmin": true },
        { "name": "user" },
        { "name": "vip_user", "isA": "user" },
        { "name": "guest", "isGuest": true }
    ],
    "database": {
        "dbms": "MySQL",
        "name": "test_db",
        "host": "localhost",
        "port": 3306,
        "prefix": "api_",
        "admin": {
            "name": "root",
            "password": "root"
        }
    },
    "types": [{
        "name": "email",
        "type": "string",
        "min": 3,
        "pattern": "/^(?!(?:(?:\\x22?\\x5C[\\x00-\\x7E]\\x22?)|(?:\\x22?[^\\x5C\\x22]\\x22?)){255,})(?!(?:(?:\\x22?\\x5C[\\x00-\\x7E]\\x22?)|(?:\\x22?[^\\x5C\\x22]\\x22?)){65,}@)(?:(?:[\\x21\\x23-\\x27\\x2A\\x2B\\x2D\\x2F-\\x39\\x3D\\x3F\\x5E-\\x7E]+)|(?:\\x22(?:[\\x01-\\x08\\x0B\\x0C\\x0E-\\x1F\\x21\\x23-\\x5B\\x5D-\\x7F]|(?:\\x5C[\\x00-\\x7F]))*\\x22))(?:\\.(?:(?:[\\x21\\x23-\\x27\\x2A\\x2B\\x2D\\x2F-\\x39\\x3D\\x3F\\x5E-\\x7E]+)|(?:\\x22(?:[\\x01-\\x08\\x0B\\x0C\\x0E-\\x1F\\x21\\x23-\\x5B\\x5D-\\x7F]|(?:\\x5C[\\x00-\\x7F]))*\\x22)))*@(?:(?:(?!.*[^.]{64,})(?:(?:(?:xn--)?[a-z0-9]+(?:-[a-z0-9]+)*\\.){1,126}){1,}(?:(?:[a-z][a-z0-9]*)|(?:(?:xn--)[a-z0-9]+))(?:-[a-z0-9]+)*)|(?:\\[(?:(?:IPv6:(?:(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){7})|(?:(?!(?:.*[a-f0-9][:\\]]){7,})(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,5})?::(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,5})?)))|(?:(?:IPv6:(?:(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){5}:)|(?:(?!(?:.*[a-f0-9]:){5,})(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,3})?::(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,3}:)?)))?(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))(?:\\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))){3}))\\]))$/iD"
    }],
    "resources": [{
        "name": "book",
        "description": "Bunch of pages glued together.",
        "fields": [{
            "name": "title",
            "description": "Title of the book.",
            "type": "string",
            "required": true,
            "min": 1,
            "max": 300
        }, {
            "name": "author",
            "description": "Person who wrote the book.",
            "type": "string",
            "required": true,
            "min": 1,
            "max": 300,
            "default": "Anon."
        }]
    }, {
        "name": "author",
        "fields": [{
            "name": "mail",
            "type": "email"
        }]
    }]
}
